# Generated by Django 5.1.4 on 2024-12-18 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Daerah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Klinik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('nomor', models.CharField(max_length=20)),
                ('alamat', models.CharField(max_length=200)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('daerah', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pendaftaran.daerah')),
            ],
        ),
        migrations.CreateModel(
            name='Pendaftaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('nim', models.CharField(max_length=30)),
                ('jenis_kelamin', models.CharField(max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Menunggu', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('daerah', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pendaftaran.daerah')),
                ('klinik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pendaftaran.klinik')),
            ],
        ),
    ]
